name: dart_spider
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  http: ^0.13.4
  html: ^0.15.0
  sqlite3: ^1.7.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
